import 'package:bookslane_app/features/shop/domain/entities/shop_book.dart';

/// MOCKUP data for the Shop design. Replace with the Shop API.
abstract final class SampleShopBooks {
  /// The one real thinkerslane cover we know resolves, so the mockup shows
  /// how a photographed cover sits in the tile next to generated ones.
  static const String _thinkerslaneCover =
      'https://thinkerslane.com/public/uploads/admin/books/2025/01/img_6a71bdd436faa0.08144594.jpg';

  /// Upper end of the price slider.
  static const double maxPrice = 1000;

  static final List<ShopBook> all = [
    ShopBook(
      id: 's1',
      title: 'Baitalik',
      author: 'Rabindranath Tagore',
      sku: 'TL-POE-3244',
      category: ShopCategory.poetry,
      language: ShopLanguage.bengali,
      mrp: 250,
      price: 200,
      stock: 12,
      addedOn: DateTime(2026, 9, 2),
      featuredRank: 1,
      imageUrl: _thinkerslaneCover,
    ),
    ShopBook(
      id: 's2',
      title: 'The Last Lighthouse',
      author: 'Elin Norberg',
      sku: 'BL-FIC-1048',
      category: ShopCategory.fiction,
      language: ShopLanguage.english,
      mrp: 499,
      price: 399,
      stock: 24,
      addedOn: DateTime(2026, 8, 14),
      featuredRank: 2,
    ),
    ShopBook(
      id: 's3',
      title: 'Quiet Spaces',
      author: 'Maya Lind',
      sku: 'BL-LIF-2071',
      category: ShopCategory.lifestyle,
      language: ShopLanguage.english,
      mrp: 650,
      price: 520,
      stock: 8,
      addedOn: DateTime(2026, 9, 10),
      featuredRank: 3,
    ),
    ShopBook(
      id: 's4',
      title: 'Nordic Table',
      author: 'Erik Dahl',
      sku: 'BL-FOD-3320',
      category: ShopCategory.food,
      language: ShopLanguage.english,
      mrp: 799,
      price: 640,
      stock: 5,
      addedOn: DateTime(2026, 7, 30),
      featuredRank: 4,
    ),
    ShopBook(
      id: 's5',
      title: 'Moon Bear',
      author: 'Liv Anders',
      sku: 'BL-KID-0187',
      category: ShopCategory.kids,
      language: ShopLanguage.english,
      mrp: 299,
      price: 240,
      stock: 0,
      addedOn: DateTime(2026, 6, 18),
      featuredRank: 5,
    ),
    ShopBook(
      id: 's6',
      title: 'Aranyak',
      author: 'Bibhutibhushan Bandyopadhyay',
      sku: 'TL-FIC-1120',
      category: ShopCategory.fiction,
      language: ShopLanguage.bengali,
      mrp: 350,
      price: 350,
      stock: 40,
      addedOn: DateTime(2026, 9, 18),
      featuredRank: 6,
    ),
    ShopBook(
      id: 's7',
      title: 'A Northern Winter',
      author: 'Sofia Ek',
      sku: 'BL-FIC-1092',
      category: ShopCategory.fiction,
      language: ShopLanguage.english,
      mrp: 450,
      price: 360,
      stock: 16,
      addedOn: DateTime(2026, 5, 3),
      featuredRank: 7,
    ),
    ShopBook(
      id: 's8',
      title: 'The Thoughtful Home',
      author: 'Oskar Nyman',
      sku: 'BL-LIF-2114',
      category: ShopCategory.lifestyle,
      language: ShopLanguage.english,
      mrp: 699,
      price: 560,
      stock: 3,
      addedOn: DateTime(2026, 8, 1),
      featuredRank: 8,
    ),
    ShopBook(
      id: 's9',
      title: 'Godaan',
      author: 'Munshi Premchand',
      sku: 'TL-FIC-0910',
      category: ShopCategory.fiction,
      language: ShopLanguage.hindi,
      mrp: 320,
      price: 280,
      stock: 0,
      addedOn: DateTime(2026, 4, 22),
      featuredRank: 9,
    ),
    ShopBook(
      id: 's10',
      title: 'Small Habits, Big Days',
      author: 'Ananya Rao',
      sku: 'TL-NFI-4402',
      category: ShopCategory.nonFiction,
      language: ShopLanguage.english,
      mrp: 399,
      price: 399,
      stock: 30,
      addedOn: DateTime(2026, 9, 21),
      featuredRank: 10,
    ),
  ];
}
